# Generated by Django 4.2.7 on 2023-11-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audioManager", "0002_alter_dropboxtoken_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=200, unique=True)),
                ("size", models.DateTimeField(blank=True, null=True)),
                ("is_downloadble", models.BooleanField()),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
