# Generated by Django 4.2.7 on 2023-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audioManager", "0003_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
